[package]
name = "game_of_life"
version = "0.1.0"
authors = ["Nick Dolan <nicholas.dolan1@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "game-bench"
harness = false